# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ip_option = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_option.setObjectName("ip_option")
        self.horizontalLayout.addWidget(self.ip_option)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.port_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.port_1.setMaximum(1000000000)
        self.port_1.setProperty("value", 5000)
        self.port_1.setObjectName("port_1")
        self.horizontalLayout.addWidget(self.port_1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.port_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.port_2.setMaximum(1000000000)
        self.port_2.setProperty("value", 6000)
        self.port_2.setObjectName("port_2")
        self.horizontalLayout.addWidget(self.port_2)
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout.addWidget(self.connect_button)
        self.disconnect_button = QtWidgets.QPushButton(self.centralwidget)
        self.disconnect_button.setObjectName("disconnect_button")
        self.horizontalLayout.addWidget(self.disconnect_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.reset_button = QtWidgets.QPushButton(self.layoutWidget)
        self.reset_button.setObjectName("reset_button")
        self.verticalLayout.addWidget(self.reset_button)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stop_auto_mode_button = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_auto_mode_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_auto_mode_button.sizePolicy().hasHeightForWidth())
        self.stop_auto_mode_button.setSizePolicy(sizePolicy)
        self.stop_auto_mode_button.setObjectName("stop_auto_mode_button")
        self.horizontalLayout_6.addWidget(self.stop_auto_mode_button)
        self.auto_mode_button = QtWidgets.QPushButton(self.layoutWidget)
        self.auto_mode_button.setObjectName("auto_mode_button")
        self.horizontalLayout_6.addWidget(self.auto_mode_button)
        self.auto_mode_startup_option = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_mode_startup_option.sizePolicy().hasHeightForWidth())
        self.auto_mode_startup_option.setSizePolicy(sizePolicy)
        self.auto_mode_startup_option.setChecked(True)
        self.auto_mode_startup_option.setObjectName("auto_mode_startup_option")
        self.horizontalLayout_6.addWidget(self.auto_mode_startup_option)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.wafer_table = QtWidgets.QTableWidget(self.layoutWidget)
        self.wafer_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.wafer_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.wafer_table.setObjectName("wafer_table")
        self.wafer_table.setColumnCount(3)
        self.wafer_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.wafer_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wafer_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.wafer_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.wafer_table)
        self.test_button_layout = QtWidgets.QHBoxLayout()
        self.test_button_layout.setObjectName("test_button_layout")
        self.verticalLayout.addLayout(self.test_button_layout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mv_w_id_option = QtWidgets.QComboBox(self.layoutWidget)
        self.mv_w_id_option.setObjectName("mv_w_id_option")
        self.horizontalLayout_5.addWidget(self.mv_w_id_option)
        self.to_option = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_option.sizePolicy().hasHeightForWidth())
        self.to_option.setSizePolicy(sizePolicy)
        self.to_option.setObjectName("to_option")
        self.to_option.addItem("")
        self.to_option.addItem("")
        self.to_option.addItem("")
        self.to_option.addItem("")
        self.to_option.addItem("")
        self.to_option.addItem("")
        self.to_option.addItem("")
        self.to_option.addItem("")
        self.horizontalLayout_5.addWidget(self.to_option)
        self.mv_w_button = QtWidgets.QPushButton(self.layoutWidget)
        self.mv_w_button.setObjectName("mv_w_button")
        self.horizontalLayout_5.addWidget(self.mv_w_button)
        self.virtual_reply_button = QtWidgets.QPushButton(self.layoutWidget)
        self.virtual_reply_button.setObjectName("virtual_reply_button")
        self.horizontalLayout_5.addWidget(self.virtual_reply_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_option = QtWidgets.QLineEdit(self.layoutWidget)
        self.text_option.setObjectName("text_option")
        self.horizontalLayout_2.addWidget(self.text_option)
        self.send_button = QtWidgets.QPushButton(self.layoutWidget)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout_2.addWidget(self.send_button)
        self.clear_button_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.clear_button_1.setObjectName("clear_button_1")
        self.horizontalLayout_2.addWidget(self.clear_button_1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.console_1 = QtWidgets.QTextBrowser(self.layoutWidget)
        self.console_1.setObjectName("console_1")
        self.verticalLayout.addWidget(self.console_1)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.data_limit_table = QtWidgets.QTableWidget(self.layoutWidget1)
        self.data_limit_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.data_limit_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.data_limit_table.setObjectName("data_limit_table")
        self.data_limit_table.setColumnCount(3)
        self.data_limit_table.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.data_limit_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_limit_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_limit_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_limit_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_limit_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_limit_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_limit_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.data_limit_table)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.mv_counter = QtWidgets.QSpinBox(self.layoutWidget1)
        self.mv_counter.setEnabled(False)
        self.mv_counter.setObjectName("mv_counter")
        self.horizontalLayout_4.addWidget(self.mv_counter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.clear_button_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.clear_button_2.setObjectName("clear_button_2")
        self.horizontalLayout_4.addWidget(self.clear_button_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.console_2 = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.console_2.setObjectName("console_2")
        self.verticalLayout_2.addWidget(self.console_2)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.clear_button_1.clicked.connect(self.console_1.clear)
        self.clear_button_2.clicked.connect(self.console_2.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Socket Client"))
        self.label.setText(_translate("MainWindow", "IP:"))
        self.ip_option.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_2.setText(_translate("MainWindow", "port 1:"))
        self.label_3.setText(_translate("MainWindow", "port 2:"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.disconnect_button.setText(_translate("MainWindow", "Disconnect"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.stop_auto_mode_button.setText(_translate("MainWindow", "Stop"))
        self.auto_mode_button.setText(_translate("MainWindow", "Auto Mode"))
        self.auto_mode_startup_option.setText(_translate("MainWindow", "Auto startup"))
        item = self.wafer_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Wafer ID"))
        item = self.wafer_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Position"))
        item = self.wafer_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        self.to_option.setItemText(0, _translate("MainWindow", "A"))
        self.to_option.setItemText(1, _translate("MainWindow", "B"))
        self.to_option.setItemText(2, _translate("MainWindow", "C"))
        self.to_option.setItemText(3, _translate("MainWindow", "D"))
        self.to_option.setItemText(4, _translate("MainWindow", "E"))
        self.to_option.setItemText(5, _translate("MainWindow", "F"))
        self.to_option.setItemText(6, _translate("MainWindow", "CassA"))
        self.to_option.setItemText(7, _translate("MainWindow", "CassB"))
        self.mv_w_button.setText(_translate("MainWindow", "Move Wafer"))
        self.virtual_reply_button.setText(_translate("MainWindow", "Virtual Reply"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.clear_button_1.setText(_translate("MainWindow", "Clear"))
        item = self.data_limit_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "B"))
        item = self.data_limit_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "D"))
        item = self.data_limit_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "E"))
        item = self.data_limit_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "F"))
        item = self.data_limit_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Win Out"))
        item = self.data_limit_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Win In"))
        item = self.data_limit_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time"))
        self.label_4.setText(_translate("MainWindow", "Steps:"))
        self.clear_button_2.setText(_translate("MainWindow", "Clear"))

